openapi: 3.1.0
x-stoplight:
  id: x0ygm9j5iky4x
info:
  title: pilote-api
  version: '1.0'
  summary: Cette API permet d'interagir avec Pilote.
  description: 'Via cette API, il est possible de récupérer les données de Pilote et d''importer des données dans la limite des autorisations fixées par votre compte.'
  contact:
    name: Colin DUGEAI
    email: colin.dugeaiATmodernisation.gouv.fr
servers:
  - url: 'http://localhost:3000'
    description: Local
  - url: 'http://172.17.0.1:3000'
    description: Docker local
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
  '/chantier/{chantier_id}':
    parameters:
      - schema:
          type: string
        name: chantier_id
        in: path
        required: true
    get:
      summary: Informations chantier
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chantier'
              examples:
                Example 1:
                  value:
                    id: CH-001
                    description: Description textuelle du premier chantier
                    nom: Premier chantier prioritaire
                    directeur_projet: Jean Dupont
                    ppg_id: PPG-123
                    porteurs: MEFSIN | MSAPH
                    perimetre_id: PER-019
                    territorialise: true
                    engagement: EMPLOI
                    etat: PUBLIE
      operationId: get-chantier-id
      description: Obtenir les informations sur un chantier
      parameters: []
    post:
      summary: Modifier un chantier
      operationId: post-chantier-id
      responses:
        '200':
          description: OK
      description: Obtenir les informations sur un chantier
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
      x-stoplight:
        id: zli1xhb85ytzu
    Chantier:
      title: Chantier
      x-stoplight:
        id: p5jtbeh5h8v1h
      type: object
      description: Description complète d'un chantier prioritaire.
      examples:
        - id: CH-001
          description: Description textuelle du premier chantier
          nom: Premier chantier prioritaire
          directeur_projet: Jean Dupont
          ppg_id: PPG-123
          porteurs: MEFSIN | MSAPH
          perimetre_id: PER-019
          territorialise: true
          engagement: EMPLOI
          etat: PUBLIE
      properties:
        id:
          type: string
          description: Identifiant du chantier
          pattern: '^CH-[0-9][0-9][0-9]$'
        description:
          type: string
          x-stoplight:
            id: zdi3an2y785p5
          description: Description du chantier
        nom:
          type: string
          x-stoplight:
            id: cyz7ea8cxcy1a
          description: Nom du chantier
        directeur_projet:
          type: string
          x-stoplight:
            id: r49po0dyvgn0n
          description: Nom du directeur de projet
        ppg_id:
          x-stoplight:
            id: ztoyprmidlw0v
          description: Identifiant de la PPG
          type: string
          pattern: '^PPG-[0-9][0-9][0-9]$'
          example: PPG-001
        porteurs:
          type: string
          x-stoplight:
            id: zyifvj48w8g4s
          description: Liste des porteurs du chantier (séparés par " | ").
          example: MEFSIN | MSAPH
        perimetre_id:
          type: string
          x-stoplight:
            id: q2f4thq23mxe4
          example: PER-019
          pattern: '^PER-[0-9][0-9][0-9]$'
          description: Identifiant du périmètre du chantier
        territorialise:
          type: boolean
          x-stoplight:
            id: osknraxgj0nzn
          description: Etat de territorialisation du chantier (Oui/non)
        engagement:
          type: string
          x-stoplight:
            id: tx1xg9r1jx1e3
          enum:
            - EMPLOI
            - PROGRES
            - TE
            - ENGAG
          example: EMPLOI
          description: Engagement auquel appartient le chantier
        etat:
          type: string
          x-stoplight:
            id: r5xhoq4owsiaw
          enum:
            - PUBLIE
            - BROUILLON
            - NON_PUBLIE
          example: PUBLIE
          description: Etat de publication du chantier
      required:
        - id
        - description
        - nom
        - ppg_id
        - perimetre_id
        - territorialise
        - etat
      x-tags:
        - Chantier
    PPG:
      title: PPG
      x-stoplight:
        id: y5p9457oy9ahb
      type: object
      examples:
        - id: PPG-014
          nom: Première PPG
          description: Description de la PPG
          axe_id:
            id: EMPLOI
      properties:
        id:
          type: string
          description: Identifiant de la PPG
          pattern: '^PPG-[0-9][0-9][0-9]$'
          example: PPG-014
        nom:
          type: string
          x-stoplight:
            id: 38z6p01nyhsyz
          example: Mieux vivre de son travail
        description:
          type: string
          x-stoplight:
            id: q86g1ouyl59k9
        axe_id:
          $ref: '#/components/schemas/Axe'
          x-stoplight:
            id: 4tdqltir7n7y4
      required:
        - id
        - nom
    Axe:
      title: Axe
      x-stoplight:
        id: pkmunivqndbww
      type: object
      properties:
        id:
          type: string
          example: EMPLOI
  securitySchemes:
    abc-123:
      name: X-API-KEY
      type: apiKey
      in: header
      description: Cette clé d'API vous permet de vous authentifier et d'aacéder uniquement aux resources autorisées.
  parameters:
    chantier_id:
      name: chantier_id
      in: query
      schema:
        type: string
        pattern: bla
      description: Identifiant de chantier
      required: true
x-internal: false
